import type { ControlCenterSnapshot } from "./domain.ts";

const mutationDependencyReason =
  "Writes require accepted SPEC-004 through SPEC-008 owner contracts and the SPEC-024/025 control-plane and deployment boundaries. This discardable fixture experiment does not implement those contracts and grants no mutation authority.";

export const controlCenterFixture = {
  identity: {
    fixtureId: "control-center-fixture-v1",
    authority: "fixture_non_authoritative",
    sourceSequence: 1_148,
    eventChainDigest:
      "sha256:6be94f579a284735f1eef2ea846add45ff9daf2a0e1118583d19988db194d275",
    asOfObservationId: "clock-observation-fixture-20260824t184500z",
    asOf: "2026-08-24T18:45:00Z",
    freshness: {
      state: "current",
      observedAt: "2026-08-24T18:45:00Z",
    },
  },
  health: [
    {
      id: "repository",
      label: "Repository checks",
      value: "Passing",
      tone: "good",
      detail: "Fabricated baseline fixture reports the required validation suite as passing.",
    },
    {
      id: "review",
      label: "Review queue",
      value: "3 waiting",
      tone: "warning",
      detail: "Human review remains the decision boundary.",
    },
    {
      id: "runtime",
      label: "Runtime authority",
      value: "Inactive",
      tone: "neutral",
      detail: "Draft owner specifications do not authorize continuous execution.",
    },
    {
      id: "deployment",
      label: "Deployment",
      value: "Not activated",
      tone: "warning",
      detail: "SPEC-025 revision 1 is a draft and no active deployment pointer exists.",
    },
  ],
  repositoryAcceptance: {
    state: "known",
    value: "c6cd520 (fabricated baseline fixture)",
    sourceEvent: "repository-baseline-fixture-1",
  },
  organizationVersion: {
    state: "dependency_inactive",
    owner: "SPEC-019",
    requiredRevision: 1,
    reasonCode: "owner_spec_not_accepted",
  },
  deploymentPointer: {
    state: "dependency_inactive",
    owner: "SPEC-025",
    requiredRevision: 1,
    reasonCode: "owner_spec_not_accepted",
  },
  runs: [
    {
      id: "run-context-routing-08",
      objective: "Evaluate routing precision after corpus hardening",
      state: "awaiting_review",
      currentStage: "independent review",
      owner: "evaluation steward",
      updatedAt: "2026-08-24T18:31:00Z",
      evidenceCount: 18,
      completionPercent: 88,
      blocker: {
        reasonCode: "human_review_required",
        detail: "The sealed evaluation needs an independent human decision.",
      },
    },
    {
      id: "run-retrieval-boundaries-03",
      objective: "Stress-test bounded retrieval and evidence closure",
      state: "novelty_check",
      currentStage: "novelty check",
      owner: "research steward",
      updatedAt: "2026-08-24T17:54:00Z",
      evidenceCount: 31,
      completionPercent: 64,
    },
    {
      id: "run-production-canary-01",
      objective: "Exercise the production canary and recovery matrix",
      state: "blocked_dependency",
      currentStage: "not dispatchable",
      owner: "operations steward",
      updatedAt: "2026-08-24T16:10:00Z",
      evidenceCount: 0,
      completionPercent: 0,
      blocker: {
        reasonCode: "dependency_inactive",
        detail: "SPEC-025 and its prerequisite contracts are not accepted or active.",
      },
    },
  ],
  reviewQueue: [
    {
      id: "review-pr-train-121-131",
      kind: "pull_request",
      title: "Linear governance PR train #121–#131",
      state: "needs_human_review",
      risk: "high",
      checks: { passed: 11, total: 11 },
      submittedAt: "2026-08-24T15:00:00Z",
      decisionOwner: "human maintainer",
      blocker: "Sequential merge-commit review is required; fixture status is not GitHub truth.",
    },
    {
      id: "review-runtime-boundaries",
      kind: "candidate",
      title: "Fail-closed legacy runtime hardening",
      state: "ready_for_decision",
      risk: "medium",
      checks: { passed: 14, total: 14 },
      submittedAt: "2026-08-24T16:42:00Z",
      decisionOwner: "independent release reviewer",
    },
    {
      id: "review-spec-000-r2",
      kind: "specification",
      title: "SPEC-000 revision 2 authority vocabulary",
      state: "blocked_dependency",
      risk: "high",
      checks: { passed: 0, total: 6 },
      submittedAt: "2026-08-24T17:18:00Z",
      decisionOwner: "human maintainer",
      blocker: "The amendment has not entered its review lifecycle.",
    },
  ],
  artifacts: [
    {
      id: "artifact-inventory-c9adc44f",
      kind: "CorpusInventory",
      name: "Canonical corpus inventory",
      classification: "public_derived",
      digest:
        "sha256:c9adc44f0bcc8d1d74977933b6f6df47646d1cecf9da5d69861ada914d0ee3c8",
      bytes: 428_116,
      createdAt: "2026-08-24T18:02:00Z",
      integrity: "verified",
      lineage: "266 declared input snapshots → 335 artifact records",
    },
    {
      id: "artifact-eval-freeze-572a",
      kind: "FreezeReceipt",
      name: "Router evaluation editable-surface freeze",
      classification: "private",
      digest:
        "sha256:572a8e52b7edc29f4a82eea557d55f1b67a52ee1b79d17445a17f371f752caf3",
      bytes: 9_842,
      createdAt: "2026-08-24T17:51:00Z",
      integrity: "verified",
      lineage: "Candidate bytes + policy digest + editable-surface declaration",
    },
    {
      id: "artifact-canary-plan-19c1",
      kind: "CanaryPlan",
      name: "Supervised-control deployment drill plan",
      classification: "private",
      digest:
        "sha256:19c1b50f61f181c6ca989f02aa07ed1cc2dbd4ecb890e39e6762f0445fe7b1d6",
      bytes: 12_288,
      createdAt: "2026-08-24T16:33:00Z",
      integrity: "unverified",
      lineage: "Draft SPEC-025 fixture; carries no deployment authority",
    },
  ],
  deployment: {
    lifecycle: "dependency_inactive",
    target: "supervised_local_control_remote_untrusted",
    ownerSpec: "SPEC-025",
    requiredRevision: 1,
    activeCommit: {
      state: "dependency_inactive",
      owner: "SPEC-025",
      requiredRevision: 1,
      reasonCode: "owner_spec_not_accepted",
    },
    processManager: "launchd",
    supervisor: "orgd",
    interactionMode: "read_only_fixture",
    resultPath: "Journal events → projections → immutable ArtifactRef records",
    topology: [
      {
        id: "operator",
        label: "Human operator",
        detail: "Owns approval, credentials, activation, and emergency authority.",
        boundary: "operator",
      },
      {
        id: "control-center",
        label: "Control Center",
        detail: "Read-only server-rendered projection in this slice.",
        boundary: "operator",
      },
      {
        id: "orgd",
        label: "orgd supervisor",
        detail: "Future local scheduler, reconciler, projector, and outbox. It does not execute untrusted code.",
        boundary: "supervisor",
      },
      {
        id: "executors",
        label: "Worker routing boundary",
        detail: "Trusted deterministic and bounded work may use local children; untrusted code or tools must route to a remote accepted GKE sandbox.",
        boundary: "worker",
      },
      {
        id: "durable-state",
        label: "Journal + content-addressed artifacts",
        detail: "Future canonical events, immutable receipts, and rebuildable views.",
        boundary: "storage",
      },
    ],
    readiness: [
      {
        id: "deterministic-validation",
        label: "Deterministic repository validation",
        state: "passed",
        evidence: "Fixture evidence only; rerun on the frozen deploy candidate.",
      },
      {
        id: "authority-contracts",
        label: "Accepted authority and runtime contracts",
        state: "blocked",
        evidence: "SPEC-004–SPEC-025 dependencies are not active.",
      },
      {
        id: "experiment-lifecycle",
        label: "Lifecycle authority for this design experiment",
        state: "blocked",
        evidence: "This discardable fixture is not implementation evidence. If lifecycle policy classifies it as prototype work, it requires explicit review before shipping.",
      },
      {
        id: "backup-restore-drill",
        label: "Clean-directory backup and restore drill",
        state: "not_run",
        evidence: "Requires a sealed deployment manifest and durable journal implementation.",
      },
      {
        id: "kill-matrix",
        label: "External-effect crash and reconciliation matrix",
        state: "not_run",
        evidence: "No production executor is authorized in this slice.",
      },
      {
        id: "canary-attestation",
        label: "Independent closed-window canary attestation",
        state: "blocked",
        evidence: "Activation path is owned by draft SPEC-025.",
      },
    ],
  },
  readinessAssessment: {
    sourceDocument: "docs/product/production-readiness.json",
    authoritative: false,
    productionReady: false,
    baselineCommit: "c6cd52017b247804373339e1c3c103d42554b0a1",
    candidateState: "uncommitted_worktree",
    candidateCommit: null,
    notice:
      "Static fixture mirror of the product assessment authority envelope. It is a discardable design experiment, not an implementation of draft owner specifications, and cannot authorize implementation, activation, promotion, merge, or deployment.",
  },
  events: [
    {
      sequence: 1_141,
      id: "evt-fixture-1141",
      occurredAt: "2026-08-24T17:51:00Z",
      kind: "artifact.verified",
      subject: "artifact-eval-freeze-572a",
      summary: "Editable-surface freeze receipt verified.",
      severity: "info",
    },
    {
      sequence: 1_142,
      id: "evt-fixture-1142",
      occurredAt: "2026-08-24T17:54:00Z",
      kind: "run.transitioned",
      subject: "run-retrieval-boundaries-03",
      summary: "Run entered novelty check.",
      severity: "info",
    },
    {
      sequence: 1_143,
      id: "evt-fixture-1143",
      occurredAt: "2026-08-24T18:02:00Z",
      kind: "inventory.generated",
      subject: "artifact-inventory-c9adc44f",
      summary: "Canonical fixture inventory digest recorded.",
      severity: "info",
    },
    {
      sequence: 1_144,
      id: "evt-fixture-1144",
      occurredAt: "2026-08-24T18:10:00Z",
      kind: "dependency.denied",
      subject: "run-production-canary-01",
      summary: "Dispatch denied because the deployment owner contract is inactive.",
      severity: "warning",
    },
    {
      sequence: 1_145,
      id: "evt-fixture-1145",
      occurredAt: "2026-08-24T18:22:00Z",
      kind: "review.requested",
      subject: "review-runtime-boundaries",
      summary: "Independent release review requested.",
      severity: "info",
    },
    {
      sequence: 1_146,
      id: "evt-fixture-1146",
      occurredAt: "2026-08-24T18:31:00Z",
      kind: "run.blocked",
      subject: "run-context-routing-08",
      summary: "Run is waiting for human review.",
      severity: "warning",
    },
    {
      sequence: 1_147,
      id: "evt-fixture-1147",
      occurredAt: "2026-08-24T18:39:00Z",
      kind: "projection.rebuilt",
      subject: "status-fixture-1147",
      summary: "Read-only fixture projection rebuilt.",
      severity: "info",
    },
    {
      sequence: 1_148,
      id: "evt-fixture-1148",
      occurredAt: "2026-08-24T18:45:00Z",
      kind: "clock.observed",
      subject: "clock-observation-fixture-20260824t184500z",
      summary: "Fixture observation closed the status prefix.",
      severity: "info",
    },
  ],
  capabilities: [
    {
      action: "pause_run",
      enabled: false,
      reasonCode: "dependency_inactive",
      reason: mutationDependencyReason,
      ownerSpecs: ["SPEC-004", "SPEC-005", "SPEC-006"],
    },
    {
      action: "resume_run",
      enabled: false,
      reasonCode: "dependency_inactive",
      reason: mutationDependencyReason,
      ownerSpecs: ["SPEC-004", "SPEC-005", "SPEC-006"],
    },
    {
      action: "record_review_decision",
      enabled: false,
      reasonCode: "dependency_inactive",
      reason: mutationDependencyReason,
      ownerSpecs: ["SPEC-006", "SPEC-007", "SPEC-024"],
    },
    {
      action: "activate_deployment",
      enabled: false,
      reasonCode: "dependency_inactive",
      reason: mutationDependencyReason,
      ownerSpecs: ["SPEC-019", "SPEC-024", "SPEC-025"],
    },
  ],
} as const satisfies ControlCenterSnapshot;
